- name: deploy mongodb PV
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: mongo-pv # name of PV
        namespace: default
      spec:
        capacity:
          storage: 1Gi
        hostPath:
          path: /tmp/mongo
        storageClassName: db
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Delete
- name: deploy mongodb PVC
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mongo-pvc
        namespace: default
      spec:
        storageClassName: db
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 256Mi
- name: deploy mongo service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: mongo
        namespace: default
      spec:
        selector:
          app: mongo
        ports:
          - port: 27017
            targetPort: 27017
- name: deploy mongodb
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mongo
        namespace: default
      spec:
        selector:
          matchLabels:
            app: mongo
        template:
          metadata:
            labels:
              app: mongo
          spec:
            containers:
              - name: mongo
                image: mongo
                ports:
                  - containerPort: 27017
                volumeMounts:
                  - name: storage
                    mountPath: /data/db
            volumes:
              - name: storage
                persistentVolumeClaim:
                  claimName: mongo-pvc
              
